---
name: Python Checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call-python-checks:
    name: Call Python Checks

    uses: geocoug/github-actions-templates/.github/workflows/python-checks.yml@main

    permissions:
      contents: read

    with:
      pytest: false
